package com.example.bettertrialbook.models;

import android.location.Location;
import android.os.Parcel;
import android.os.Parcelable;

/**
 * Geolocation class stores a location object containing the lat and lon of the trial's geolocation.
 * We chose to create a Geolocation class so that if we ever need to add more attributes aside from location
 * to a Geolocation, the structure for doing so is already implemented.
 * The class implements Parcelable so that it can be easily passed through intents between activities.
 * It implements Comparable for easy comparisons with itself.
 */
public class Geolocation implements Parcelable, Comparable<Geolocation> {
    Location location;

    /**
     * Creates a Geolocation
     * @param location
     *  the location of the Geolocation
     */
    public Geolocation(Location location) {
        this.location = location;
    }

    /**
     * gets the Geolocation's location
     * @return
     *  the location
     */
    public Location getLocation() {
        return location;
    }

    /**
     * sets the Geolocation's location
     * @param location
     *  the location to set
     */
    public void setLocation(Location location) {
        this.location = location;
    }

    // Comparable implementation

    /**
     * This overrides the compareTo method from Comparable,
     * making it so that we can compare Geolocation objects
     * @param geolocation
     *  The geolocation being compared to
     * @return
     *  Returns 0 if the Geolocations are equal, non-zero otherwise
     */
    @Override
    public int compareTo(Geolocation geolocation) {
        return String.valueOf(this.location.getLatitude()).compareTo(String.valueOf(geolocation.getLocation().getLatitude()))
                + String.valueOf(this.location.getLongitude()).compareTo(String.valueOf(geolocation.getLocation().getLongitude()));
    }

    // Parcelable implementation, for the most part auto generated by Android Studio

    /**
     * The Constructor used for passing a Parcel
     * @param in
     *  the Parcel being used
     */
    protected Geolocation(Parcel in) {
        location = in.readParcelable(Location.class.getClassLoader());
    }

    /**
     * The Creator method for the Parcelable implementation of Geolocation
     */
    public static final Creator<Geolocation> CREATOR = new Creator<Geolocation>() {
        @Override
        public Geolocation createFromParcel(Parcel in) {
            return new Geolocation(in);
        }

        @Override
        public Geolocation[] newArray(int size) {
            return new Geolocation[size];
        }
    };

    /**
     * the describeContents() method implemented for Parcelable implementation
     * @return
     *  0
     */
    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * Creates a parcel with the relevant information including the location of the Geolocation
     * @param dest
     *  the Parcel being created
     * @param flags
     *  any relevant flags for Parcelable implementation
     */
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeParcelable(location, flags);
    }
}
